<?xml version="1.0"?>
<package format="3">
  <name>dextivr_hande_deploy</name>
  <version>0.0.1</version>
  <description>
    3D models of the Hand-E gripper for simulation and visualization
  </description>
  <maintainer email="andrew.p.sharp@nasa.gov">Andrew Sharp</maintainer>

  <license>NASA-1.3</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend>robotiq_driver</depend>

  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">rviz</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">rviz2</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">launch</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">launch_ros</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">robotiq_driver</exec_depend>

  <export>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
